#!/bin/bash

set -eou pipefail

simple_fields=()
simple_fields_boilerplate=()
simple_fields+=('.created')
simple_fields+=('.updated')
simple_fields+=('.meta.slug')
simple_fields_boilerplate+=('.meta.slug')
simple_fields+=('.title')
simple_fields+=('.book_state')
simple_fields+=('.salesforce_abbreviation')
simple_fields+=('.salesforce_name')
simple_fields+=('.salesforce_book_id')
simple_fields+=('.book_subjects[0].subject_name')
simple_fields+=('.is_ap')
simple_fields+=('.cover_url')
simple_fields+=('.title_image_url')
simple_fields+=('.cover_color')
simple_fields+=('.book_cover_text_color')
simple_fields+=('.reverse_gradient')
simple_fields+=('.publish_date')
simple_fields+=('.print_isbn_10')
simple_fields+=('.print_isbn_13')
simple_fields+=('.print_softcover_isbn_10')
simple_fields+=('.print_softcover_isbn_13')
simple_fields+=('.digital_isbn_10')
simple_fields+=('.digital_isbn_13')
simple_fields+=('.ibook_isbn_10')
simple_fields+=('.ibook_isbn_13')
simple_fields+=('.ibook_volume_2_isbn_10')
simple_fields+=('.ibook_volume_2_isbn_13')
simple_fields_boilerplate+=('.license_text')
simple_fields_boilerplate+=('.license_name')
simple_fields_boilerplate+=('.license_version')
simple_fields+=('.license_url')
simple_fields+=('.high_resolution_pdf_url')
simple_fields+=('.low_resolution_pdf_url')
simple_fields_boilerplate+=('.community_resource_heading')
simple_fields_boilerplate+=('.community_resource_logo_url')
simple_fields+=('.community_resource_url')
simple_fields_boilerplate+=('.community_resource_cta')
simple_fields_boilerplate+=('.community_resource_blurb')
simple_fields+=('.community_resource_feature_link_url')
simple_fields+=('.community_resource_feature_text')
simple_fields+=('.ibook_link')
simple_fields+=('.ibook_link_volume_2')
simple_fields+=('.webview_link')
simple_fields+=('.webview_rex_link')
simple_fields_boilerplate+=('.rex_callout_title')
simple_fields_boilerplate+=('.rex_callout_blurb')
simple_fields+=('.enable_study_edge')
simple_fields+=('.bookshare_link')
simple_fields+=('.amazon_coming_soon')
simple_fields+=('.amazon_link')
simple_fields+=('.kindle_link')
simple_fields+=('.chegg_link')
simple_fields+=('.chegg_link_text')
simple_fields+=('.bookstore_coming_soon')
simple_fields+=('.comp_copy_available')
simple_fields_boilerplate+=('.errata_content')
simple_fields+=('.tutor_marketing_book')
simple_fields_boilerplate+=('.partner_list_label')
simple_fields_boilerplate+=('.partner_page_link_text')
simple_fields_boilerplate+=('.customization_form_heading')
simple_fields_boilerplate+=('.customization_form_subheading')
simple_fields_boilerplate+=('.customization_form_disclaimer')
simple_fields_boilerplate+=('.customization_form_next_steps')
simple_fields+=('.seo_title')
simple_fields+=('.search_description')
# simple_fields+=('.promote_image') .meta.download_url
simple_fields+=('.last_updated_pdf')
simple_fields_boilerplate+=('.featured_resources_header')
simple_fields_boilerplate+=('.support_statement')
simple_fields+=('.adoptions')
simple_fields+=('.savings')
simple_fields+=('.cnx_id')
simple_fields+=('.description')


make_file() {
    book_json=$1
    book_slug=$2
    jq_sel_root=$3
    jq_sel_fields=$4
    out_file="output/$book_slug.$jq_sel_root.csv"

    # https://stackoverflow.com/questions/54495664/using-jq-to-create-csv-file
    output_lines=$(jq -r ".$jq_sel_root | to_entries[] | [ $jq_sel_fields ] | @csv" < "$book_json")
    if [[ $output_lines != '' ]]; then # Only write the file if we have results
        echo "$jq_sel_fields" > $out_file
        echo "$output_lines" >> $out_file
    fi
}

[[ -d ./output/ ]] && rm -rf ./output/ # First remove the output directory
[[ -d ./input/ ]] || mkdir ./input/
[[ -d ./output/ ]] || mkdir ./output/


printf -v joined '%s,' "${simple_fields[@]}"
echo "${joined%,}" > ./output/_books.csv
jq_selector="${joined%,}"

printf -v joined '%s,' "${simple_fields_boilerplate[@]}"
echo "${joined%,}" > ./output/_books.boilerplate.csv
jq_selector_boilerplate="${joined%,}"




[[ -f ./input/subjects.json ]] || curl --progress-bar --output ./input/subjects.json https://openstax.org/apps/cms/api/v2/pages/subjects/?format=json

book_ids=$(jq ".books[].id" < ./input/subjects.json)

for book_id in $book_ids; do

    book_json="./input/$book_id.book.json"

    [[ -f "$book_json" ]] || curl --progress-bar --output "$book_json" https://openstax.org/apps/cms/api/v2/pages/$book_id/?format=json

    output_line=$(jq -r "[ $jq_selector ] | @csv" < "$book_json")
    echo "$output_line" >> ./output/_books.csv

    output_line=$(jq -r "[ $jq_selector_boilerplate ] | @csv" < "$book_json")
    echo "$output_line" >> ./output/_books.boilerplate.csv

    # Write book-specific CSV files out
    book_slug=$(jq -r ".meta.slug" < "$book_json")

    echo "Working on $book_id $book_slug"

    make_file $book_json $book_slug 'book_student_resources'    '.value.resource_heading, .value.resource_description, .value.resource_unlocked, .value.resource_icon, .value.link_external, .value.link_page, .value.link_document_url, .value.link_document_title, .value.link_text, .value.coming_soon_text, .value.updated, .value.print_link, .value.display_on_k12'
    make_file $book_json $book_slug 'authors'                   '.value.value.name, .value.value.university, .value.value.country, .value.value.senior_author, .value.value.display_at_top'

    make_file $book_json $book_slug 'free_stuff_instructor'     '.value.value.heading, .value.value.content, .value.value.content_logged_in, .value.value.button_text, .value.value.button_url'
    make_file $book_json $book_slug 'free_stuff_student'        '.value.value.heading, .value.value.content, .value.value.content_logged_in, .value.value.button_text, .value.value.button_url'
    
    # make_file $book_json $book_slug 'webinar_content'           '.value.value.heading, .value.value.content, .value.value.content_logged_in, .value.value.button_text, .value.value.button_url'
    # make_file $book_json $book_slug 'bookstore_content'         '.value.value.heading, .value.value.content, .value.value.content_logged_in, .value.value.button_text, .value.value.button_url'
    # make_file $book_json $book_slug 'comp_copy_content'         '.value.value.heading, .value.value.content, .value.value.content_logged_in, .value.value.button_text, .value.value.button_url'
    
    # make_file $book_json $book_slug 'videos[0].value'             '.value.title, .value.description, .value.embed'

    make_file $book_json $book_slug 'translations'              '.value.value[0].locale, .value.value[0].slug'
    # promote_image

done